Fix output of checkout

diff --git a/cmds/checkout b/cmds/checkout
--- a/cmds/checkout
+++ b/cmds/checkout
@@ -2,16 +2,32 @@
 
 __run__() {
     gb -is-in-repo || return 1
-    
-    # TODO : check if what is passed is a branch
-    
+
+    # TODO : check if what is passed is a branch or commit
+
     (( $# == 0 )) && {
-        echo "No branch passed" >&2
+        echo "No branch/commit passed" >&2
         return 1
     }
-    
-    git checkout $1
-    return $?
+
+    git checkout $1 &> /dev/null
+    if [ $? == 1 ] ; then
+        error "failed to checkout to $1"
+        return 1
+    fi
+
+
+    local chkMsg="$(git log --oneline HEAD -n 1)"
+    if git branch | grep " $1" &> /dev/null ; then
+        echo "Switched to $(color BLUE $1) commit $(color YELLOW "$chkMsg")"
+    else
+        echo "Switched to commit $(color YELLOW "$chkMsg")"
+    fi
+
+    gb -is-detached-head && {
+        echo "$(color RED "HEAD is detached")"
+    }
+    return 0
 }
 
 __complete__() {
@@ -19,5 +35,4 @@ __complete__() {
         gb -get-branches
     fi
     return 0
-
 }
